---
kind: ReplicationController
apiVersion: v1
metadata:
    name: blue
    labels:
        app: blue
spec:
    replicas: 1
    selector:
        app: blue
    template:
        metadata:
            labels:
                app: blue
        spec:
            containers:
                - name: blue
                  image: bobbynguyen147/udacity-devops-capstone:latest
                  ports:
                      - name: http-server
                        containerPort: 80
